version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["npm", "start"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre6367@@
      POSTGRES_DB: Moozup
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
